#!/bin/bash
#SBATCH --job-name="Extract driving data from bag file"
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=2
module load python/3.6.3/virtenv
source activate ros2
cd /gpfs/space/home/rometaid/nvidia-e2e/data_extract
srun ./extract.sh /gpfs/space/projects/Bolt/bagfiles/2021-05-20-12-43-17_e2e_sulaoja_20_30.bag /gpfs/space/projects/Bolt/bagfiles/dataset
srun ./extract.sh /gpfs/space/projects/Bolt/bagfiles/2021-05-20-12-51-29_e2e_sulaoja_20_30.bag /gpfs/space/projects/Bolt/bagfiles/dataset
