#!/bin/bash
#SBATCH --job-name="Extract driving data from bag file"
#SBATCH --time=20:00:00
#SBATCH --cpus-per-task=1
#SBATCH --partition=main

#SBATCH --array=14-33
BAGS=(
        '2022-06-17-13-21-37_e2e_elva__steering.bag' \
        '2022-06-17-13-21-51_e2e_elva__steering.bag' \
        '2022-06-17-13-42-44_e2e_elva__trajectory.bag' \
        '2022-06-17-14-00-57_e2e_elva__trajectory_turn.bag' \
        '2022-06-17-14-06-10_e2e_elva__trajectory_bal.bag' \
        '2022-06-17-14-26-28_e2e_elva__steering_wide.bag' \
        '2022-06-17-14-41-00_e2e_elva__steering_wide.bag' \
        '2022-06-17-14-45-02_e2e_elva__steering_wide.bag' \
        '2022-06-17-14-51-25_e2e_elva__steering_wide_bal.bag' \
    )

module load any/python/3.8.3-conda
source activate ros2

srun ./extract_rocket_demo.sh ${BAGS[$SLURM_ARRAY_TASK_ID]}  /gpfs/space/projects/Bolt/dataset-demo-small